### ISSUE TITLE
custom gateway and option to login with either email or phone number

### ISSUE THREAD

**Issue by nnamdei** [harryanand060/Django_DRF#2]
Great work with this project.

I have a few questions; how i go about sending the generated otp in the register class to the mobile number via a custom sms gateway (a snippet would help) like the doc included below and secondly, i can see there is an option if user verified otp with email, the user can only use email to login afterwards, can that be made to allow any of them after otp verification. 
[MultiTexter_HTTP_SMS_API 2.0.pdf](https://github.com/harryanand060/django_rest/files/4709248/MultiTexter_HTTP_SMS_API.2.0.pdf)

**Comment by harryanand060** [comment]
Hi nnamdei,

Thanks, sorry for the late response. Now you can check I implemented the SMS Gateway. you can only change in **local_setting.py** with your API key and URL. 

![image](https://user-images.githubusercontent.com/16953928/83536918-86093980-a511-11ea-9764-66626d2ae68f.png)

**Note:-** I have also solved the issue of unverified device login. now only with the verified device either email or mobile user can log in.

![image](https://user-images.githubusercontent.com/16953928/83538158-214ede80-a513-11ea-8cc7-611e2caba225.png)

If you found any issue please let me know.

**Comment by nnamdei** [comment]
Thank you for the response and looking at your response, i would like to know if i am to create a function that will use the gateway in settings.py

**Comment by harryanand060** [comment]
I have already created a function for sms_getway. you can find sms_getway function inside https://github.com/harryanand060/django_rest/blob/master/account/utils/account_helper.py.
and this function called inside models class. in generate_OTP function.

**Comment by nnamdei** [comment]
I figured this out and it is currently working. Thanks for the support
